
package com.poll;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditRateServiceImpl", targetNamespace = "http://poll.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditRateServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.poll.GetCreditScoreAsyncResponse>
     */
    @WebMethod(operationName = "getCreditScoreAsync")
    @RequestWrapper(localName = "getCreditScoreAsync", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsync")
    @ResponseWrapper(localName = "getCreditScoreAsyncResponse", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsyncResponse")
    public Response<GetCreditScoreAsyncResponse> getCreditScoreAsyncAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCreditScoreAsync")
    @RequestWrapper(localName = "getCreditScoreAsync", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsync")
    @ResponseWrapper(localName = "getCreditScoreAsyncResponse", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsyncResponse")
    public Future<?> getCreditScoreAsyncAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetCreditScoreAsyncResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.poll.Score
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCreditScoreAsync", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsync")
    @ResponseWrapper(localName = "getCreditScoreAsyncResponse", targetNamespace = "http://poll.com/", className = "com.poll.GetCreditScoreAsyncResponse")
    @Action(input = "http://poll.com/CreditRateServiceImpl/getCreditScoreAsyncRequest", output = "http://poll.com/CreditRateServiceImpl/getCreditScoreAsyncResponse")
    public Score getCreditScoreAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

}
